### PR TITLE
Window Update

### PR DESCRIPTION
**Pull request by CoderPuppy**
Added a[target="_top"] clicked go in top frame (The top iframe). Added new window support (not exactly built by me).

### CODE REVIEW

**Comment by CoderPuppy** [comment]
Window stuff is written by taboca

**Comment by davidmurdoch** [comment]
Hm, this looks like it may have diverged from chromeless-sandbox-window quite a lot. I know they made some gecko2 specific changes there, specifically dealing with property/function injection. Do all these changes somehow alleviate the concerns that warranted the changes in the first place?

**Comment by CoderPuppy** [comment]
It's not all my code windows.js was originally chrome-sandbox-window.js from
taboca

**Comment by CoderPuppy** [comment]
Don't know what exactly it does but I'm pretty sure it just opens a window with the url being the `options.url`.

**Comment by CoderPuppy** [comment]
No I probably doesn't but that's just what I'm used to in jquery. Ok Will change the position.

**Comment by CoderPuppy** [comment]
Having to close to allow for using branch.

**Pull request closed without merging**
