### PR TITLE
My changes up until now, including contribution of apis and mapping of 'resource' protocol

### PR DESCRIPTION
**Pull request by mikedeboer**
Changes included in this pull request are:
- upgrade of addon-kit (jetpack) to 1.0b2
- 'path' module, modeled after NodeJS API
- 'fs' module, which extends the addon-sdk's 'file' module
- 'child_process' module, modeled after NodeJS API - when binary additions arrive in Chromeless, we should adopt https://github.com/ochameau/jetpack-subprocess, because right now it doesn't support stdin/stdout/stderr streams
- 'net' module, modeled after NodeJS API 
- mapping of the file://.../browser_code/\* to resource://app/\* (compatible with RequireJS and LABJS module loaders)

### CODE REVIEW

**Comment by Gozala** [comment]
Just a side note: I think it would make more sense to implement nodejs adapters as a separate packages that could be added as a dependencies to a give project, this would allow better code sharing between jetpack and chromeless.

**Comment by lloyd** [comment]
@mikedeboer there's lots of great stuff in here, but I'm not comfortable with a straight pull.  The reasons for that are that there's a couple places where new documentation and features were clobbered (specifically with the jetpack update).  One more area I want to look closely at is the mime detection implementation -- just yesterday I noticed that xulrunner has some type detection built in.  But these are just little details and I'm excited merge!  Thanks a ton for the contribution!

**Comment by lloyd** [comment]
@gozala 

Hey!  I was just thinking about code sharing.  It seems like in chromeless we're starting to get to the point where we're starting to build new modules at an increased rate, and some of those I would think could be beneficial to both projects.  Previously with atul an others we decided just to wait and see, but I feel like the issue is starting to get hot again.

There's two distinct topics I wanted to bring up, and maybe we should move these to the mailing list... But first is we're critically looking at documentation structure, and how we can lay things out so it makes the most sense for developers.  I'd love for you to have a look at the current proposal:  https://github.com/mozilla/chromeless/issues#issue/52

That issue is interesting because one implementation options is to use packages as a means of structuring code so developers can understand it.  The other utility of packages is a collection of code that can be shared between projects.  So the question floating around in my mind is -- Can a package be both, or should we have two different mechanisms, one that provides a logical structure for documentation (marcio proposes tags be used for this purpose), and one that facilitates sharing code (packages).

The next question is one of how documentation is written.  This is relevant because sharing is harder if different consumers have different ways of encoding docs.  Concretely, in chromeless now, docs are included in source files, while in addon-sdk they're kept in a separate .md file.  For this one I'll blog up how our new system works and drop a note on the addon-sdk list.

much love!
lloyd

**Comment by mikedeboer** [comment]
@gozala I agree! But since the packaging in Chromeless is done through a whole bunch of python scripts - and me being a complete python n00b - I didn't see another way than to add the libs to chromeless-kit like this.
Also I want to see a way to include binary extensions as well. For example, I'd like to see that a directory structure like
    chromeless-kit
      |-- data [all files in here should be copied to the 'components' directory in the app]
      |     |-- platform
      |     |     |-- Darwin_x86-gcc3 [and other ABI named directories containing binaries
      |     |                                    for that platform]
      |     |-- ipc.xpt [platform-independent .xpt files]
      |     |-- chrome.manifest [contents of the manifest file should be appended to the
      |                                   main chrome.manifest in the app]
      |-- lib [all files in here are copied as a libraries into the app]

Does this make any sense?

**Comment by mikedeboer** [comment]
@lloyd A straight pull also wasn't my intention... there's also stuff in there that I didn't even document yet, so that your docs parser would make sense of it. The resource:// uri, path and child_process are the most significant contributions.

**Comment by lloyd** [comment]
@mikedeboer Sounds good!  I'll do my best at a careful merge (perhaps on a branch) and throw the commits your way to make sure I got it right!

**Comment by lloyd** [comment]
@mikedeboer Oh, I'm very curious about binary backed modules as well.  Feel free to open a different issue with this request.  It's deep.

**Comment by mikedeboer** [comment]
Sorry for adding noise by closing and re-opening the pull request.

@lloyd, can you please check out my proposed JS API's for menus and hotkeys? I believe it now supports all the features exposed by XUL for native menus, you can see all that in test/menu. just boot it up with ./chromeless test/menu/ and you'll see the magic :) I also added a nice - if I may say so myself - API for application-wide hotkeys (or, more specifically, window-wide) that mixes nicely with menu.js.

I hope you like it!

**Comment by mikedeboer** [comment]
I also just added a commits that fixes the api-utils::inspect() function to properly inspect variables with nice colors in the console.

**Comment by lloyd** [comment]
I hand merged all changes (typically cherry picked then laid a couple commits on top where documentation was needed, or for things like mime type.

closing this pull request, please open a new one if I missed anything.

btw, you rock, mike.

**Pull request closed without merging**
