### PR TITLE
Add Cookies

### PR DESCRIPTION
**Pull request by davidmurdoch**
Here is a little script for handling cookies. getAllCookies could use some love as I really had no idea what to do with the generator/enumerator in javascript.

### CODE REVIEW

**Comment by lloyd** [comment]
you're ok with me adding an MPL license and your name as author on this lib?

**Comment by davidmurdoch** [comment]
Of course! Actually, I don't really care what you put on it. Abraham Lincoln can take the credit for all I care. :-D

**Comment by lloyd** [comment]
hah, well I'll put your name anyway, so I can blame you for things in the future.

On interesting thing is when accessing properties of returned cookies I get access errors.  I think we'll need to wrap the cookies with an object wrapper that allows app code to see inside of them.  hacking on it now...

**Comment by davidmurdoch** [comment]
I wrote the script a while back. Maybe it broke with the recent xulrunner update. I'll look into it as well.

**Comment by lloyd** [comment]
http://mozilla.github.com/chromeless/#module/chromeless-kit/cookie

**Pull request closed without merging**
