### PR TITLE
Adding support for non-printed characters to keyboard shortcuts

### PR DESCRIPTION
**Pull request by mzlee**
A small change to give support to more keyboard shortcuts.  Just a special case to let XULRunner do more.

### CODE REVIEW

**Comment by benfrancis** [comment]
This works great. What about the case of keyboard shortcuts without a modifier key like F5 and Esc?

**Comment by mzlee** [comment]
They explicitly ignore those. I'm not sure why but I'm guessing because they
don't people to replace normal letters.  I think I know how you could and
I'll look into it after work

**Comment by mzlee** [comment]
@hippygeek The chromeless code explicitly throws an error if you try to create a shortcut without a modifier.  I don't know why this is, but if there really is a need for support for f5 and escape, it can be done.

**Comment by benfrancis** [comment]
I don't think that keyboard shortcuts without a modifier is an unusual requirement for the desktop applications Chromeless is aimed at building, so IMHO this would be a sensible modification to Chromeless

**Pull request closed without merging**
