### PR TITLE
logging errors to the console (app-wide)

### PR DESCRIPTION
**Pull request by mikedeboer**
the location of this script prolly needs to be somewhere else, but it works.

### CODE REVIEW

**Comment by taboca** [comment]
I noticed our console.log ( ./tests/console/index.html ) is broken. Does not show anymore in the console. Maybe this is related to how we capture the output of the launched app?

**Comment by mikedeboer** [comment]
I guess so, I mean; it was important for me at least to see some errors! Was it usually the other way around? ie. discuss first and push later?

**Comment by taboca** [comment]
The debug part is critical! one of the most important things. Would you know how we could put Firebug to talk with this baby?

**Comment by mikedeboer** [comment]
well, firebug is another beast... it's not stable for FF4.0, thus not reliable enough to plug into chromeless imho... in Prism they did provide the inspector extension to developers, which is something we could do in chromeless as well

**Pull request merged**
